// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBogp3LB4hEjLPzpBVp2SgxkDqL__AGAl0',
    appId: '1:550818826311:android:a9f617c460e7b6e3094962',
    messagingSenderId: '550818826311',
    projectId: 'Bookfania',
    storageBucket: 'readigo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDirSA0d68SSXC9O0uww5FKGZnw_dTxg-8',
    appId: '1:550818826311:ios:745dbb7e7f15695a094962',
    messagingSenderId: '550818826311',
    projectId: 'readigo',
    storageBucket: 'readigo.firebasestorage.app',
    androidClientId: '550818826311-s28q13fk2ch4nveks1nrh8d8hvf7a25h.apps.googleusercontent.com',
    iosClientId: '550818826311-i090sj0ijbgppfhvgbgol1et9t54hnvp.apps.googleusercontent.com',
    iosBundleId: 'com.elysiahuang.testapp3',
  );

}